[package]
name = "osrs-mm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.23", features = ["derive"] }
eyre = "0.6.8"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
ureq = "2.7.1"
